// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvHzuh2Dfgu9Q8z_VbSl3ucmisKGHkUV4',
    appId: '1:569496859404:web:071b4e559292937d444f29',
    messagingSenderId: '569496859404',
    projectId: 'ua-kids-nanny',
    authDomain: 'ua-kids-nanny.firebaseapp.com',
    storageBucket: 'ua-kids-nanny.appspot.com',
    measurementId: 'G-CH7P2TWGZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_pJjQOuDztIcDXvGYfTOpsYcmTqCqBlU',
    appId: '1:569496859404:android:643d102b7522ed6f444f29',
    messagingSenderId: '569496859404',
    projectId: 'ua-kids-nanny',
    storageBucket: 'ua-kids-nanny.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKgJ4Az8fRh4NsYbDWtIYOZ1F7iY-D7_w',
    appId: '1:569496859404:ios:8555b92b2efdfe54444f29',
    messagingSenderId: '569496859404',
    projectId: 'ua-kids-nanny',
    storageBucket: 'ua-kids-nanny.appspot.com',
    androidClientId: '569496859404-pub4k0m7jbg1h95rvrgh95opn6cfg7en.apps.googleusercontent.com',
    iosClientId: '569496859404-kv4e4245l910g5d72rl9bnftnlkma9l3.apps.googleusercontent.com',
    iosBundleId: 'com.volodymyr.rykhva.nanny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKgJ4Az8fRh4NsYbDWtIYOZ1F7iY-D7_w',
    appId: '1:569496859404:ios:8555b92b2efdfe54444f29',
    messagingSenderId: '569496859404',
    projectId: 'ua-kids-nanny',
    storageBucket: 'ua-kids-nanny.appspot.com',
    androidClientId: '569496859404-pub4k0m7jbg1h95rvrgh95opn6cfg7en.apps.googleusercontent.com',
    iosClientId: '569496859404-kv4e4245l910g5d72rl9bnftnlkma9l3.apps.googleusercontent.com',
    iosBundleId: 'com.volodymyr.rykhva.nanny',
  );
}
